#!/bin/bash

DATE_CMD="gdate"

D=$($DATE_CMD +%s)

if [ $# -eq 1 ]; then
  D=$($DATE_CMD +%s --date="$1")

elif [ $# -eq 2 ]; then
  echo "Incorrect usage"
  echo "Do $0 or $0 \"some date\""
  exit 1
fi

S=1672549200

B=$(echo "scale=0; ($D - $S) * 56299000/6" | bc -lq)

R=$(gdate --date=@$D)

echo "HRD is $R"
echo "TSE is $D"
echo "BCO is $B"

