#!/bin/bash

# check if gdate is available
# if it is, use it, otherwise use date
# date works fine if it's GNU date, but BSD date may not work
if command -v gdate >/dev/null 2>&1; then
  DATE_CMD="gdate"
else
  DATE_CMD="date"
fi

get_bco_from_date()
{
  B=$(echo "scale=0; ($D - $S) * 56299000/6" | bc -lq)
}

get_date_from_bco()
{
  D=$(echo "scale=50; (6/56299000)*$B + $S" | bc -lq)
}


# set a default BCO that will get overwritten
B=0

# the exact date (time since epoch) for BCO=0
S=1672549200

# use current date as default
D=$($DATE_CMD +%s)
get_bco_from_date


# check for arguments
if [ $# -gt 0 ]; then
  # check if the input argument is a date
  if [[ "$1" == --date=* ]]; then
    INPUT_DATE="${1#--date=}"
    D=$($DATE_CMD +%s --date="$INPUT_DATE")
    # use the function to get the bco from the date
    get_bco_from_date
  # check if the input argument is a bco
  elif [[ "$1" == --bco=* ]]; then
    INPUT_BCO="${1#--bco=}"
    echo "Input bco is $INPUT_BCO"
    B=$INPUT_BCO
    # use the function to get the date from the bco
    get_date_from_bco
  fi
elif [ $# -ge 2 ]; then
  echo "Incorrect usage"
  echo "Do $0 or $0 --date=\"some date\" or $0 --bco=BCO"
  exit 1
fi


# this is partially redundant, but it will output the date in standard form, which is actually helpful information
R=$($DATE_CMD --date=@$D)

# update D to display as an integer
# no need for a dozen or more digits after the decimal when providing a bco
D=$(printf "%.0f" $D)

# human readable date
echo "HRD is $R"

# time since epoch
echo "TSE is $D"

# beam count orbit
echo "BCO is $B"

