#!/bin/bash

if command -v gdate >/dev/null 2>&1; then
  DATE_CMD="gdate"
else
  DATE_CMD="date"
fi

if [ $# -ne 1 ]; then
  echo "Incorrect usage"
  echo "Do $0 BCO to convert BCO into date"
  exit 1
fi

B=$1

S=1672549200

# 6/56299000
F=0.00000010657382902005364216060676
D=$(echo "scale=0; $F*$B + $S" | bc -lq)

D=$(printf "%.0f" $D)

R=$($DATE_CMD --date=@$D)

echo "HRD is $R"
echo "TSE is $D"
echo "BCO is $B"

