#!/bin/bash



cleanhidden=false
lscommand="ls"

if [ "$1" == "-a" ]
   then
   cleanhidden=true
   lscommand="ls -a"
fi



before=`$lscommand | wc -l`

rm *~ \#* >& /dev/null

if [[ $cleanhidden == true ]]
   then
   rm .*~ >& /dev/null
fi

after=`$lscommand | wc -l`

numcleaned=`expr $before - $after`



if [ $numcleaned -eq 0 ]
    then
    echo No files to be cleaned
fi

if [ $numcleaned -eq 1 ]
    then
    echo $numcleaned file cleaned
fi

if [ $numcleaned -gt 1 ]
    then
    echo $numcleaned files cleaned
fi
