#!/usr/bin/perl

@LIST = `ls *.HEIC`;

foreach(@LIST)
{

    $file = $_;
    chomp($file);

    $file =~ s/\.HEIC//;

    system("magick $file.HEIC -quality 95% $file.jpg");
    # add a flag here for optional deletion of HEIC
    #system("rm $file.HEIC");

}

$size = @LIST;

if ( $size == 1 )
{
    print "1 file converted \n";
}
else
{
    print "$size files converted \n";
}

