#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;

my $kill = 0;

GetOptions('k|kill' => \$kill);

my @LIST = `ls *.HEIC 2>/dev/null`;

foreach(@LIST)
{

    my $file = $_;
    chomp($file);

    $file =~ s/\.HEIC//;

    system("magick $file.HEIC -quality 95% $file.jpg");
    if ( $kill ) { system("rm $file.HEIC"); }

}

my $size_cap = @LIST;

@LIST = `ls *.heic 2>/dev/null`;

foreach(@LIST)
{

    my $file = $_;
    chomp($file);

    $file =~ s/\.heic//;

    system("magick $file.heic -quality 95% $file.jpg");
    if ( $kill ) { system("rm $file.heic"); }

}

my $size_small = @LIST;

my $size = $size_small + $size_cap;

if ( $size == 1 )
{
    print "1 file converted \n";
}
else
{
    print "$size files converted \n";
}

