#!/usr/bin/perl

use Getopt::Long;

$kill = 0;

GetOptions('k|kill' => \$kill);

@LIST = `ls *.HEIC`;

foreach(@LIST)
{

    $file = $_;
    chomp($file);

    $file =~ s/\.HEIC//;

    system("magick $file.HEIC -quality 95% $file.jpg");
    if ( $kill ) { system("rm $file.HEIC"); }

}

$size = @LIST;

if ( $size == 1 )
{
    print "1 file converted \n";
}
else
{
    print "$size files converted \n";
}

