#!/usr/bin/perl

use strict;
use warnings;



my @LIST = `ls *.jpeg 2> /dev/null`;

my $size1 = @LIST;

foreach(@LIST)
{
    my $file = $_;
    chomp($file);
    $file =~ s/\.jpeg//;
    system("mv $file.jpeg $file.jpg");
}



@LIST = `ls *.JPG 2> /dev/null`;

my $size2 = @LIST;

foreach(@LIST)
{
    my $file = $_;
    chomp($file);
    $file =~ s/\.JPG//;
    system("mv $file.JPG $file.jpg");
}



@LIST = `ls *.JPEG 2> /dev/null`;

my $size3 = @LIST;

foreach(@LIST)
{
    my $file = $_;
    chomp($file);
    $file =~ s/\.JPEG//;
    system("mv $file.JPEG $file.jpg");
}



my $size = $size1 + $size2 + $size3;

if ( $size == 1 )
{
    print "1 file changed \n";
}
else
{
    print "$size files changed \n";
}

