#!/bin/sh

#
# Examlple of using options in scripts
# Original author: vlp
# Source: https://stackoverflow.com/a/30176747
#

if [ $# -eq 0 ]
then
  echo "Missing options!"
  echo "(run $0 -h for help)"
  echo ""
  exit 0
fi

ECHO="false"

while getopts "healb" OPTION; do
  case $OPTION in
    e)
      ECHO="true"
      ;;
    a)
      echo "Option a selected, which currently does nothing"
      ;;
    l)
      echo "Option ls selected, showing files"
      ls
      ;;
    b)
      echo "Option b selected, showing current date and bco"
      bco
      ;;
    h)
      echo "Usage:"
      echo "$0 -X where X is any of the following options"
      echo ""
      echo "   -e     to execute echo \"hello world\""
      echo "   -a     to do nothing (it tells you it does nothing)"
      echo "   -b     to get the current date and bco"
      echo "   -l     to do the ls command, because why not"
      echo "   -h     help (this output)"
      echo ""
      echo "Options can be stacked in any order, such as $0 -a -b -e -l"
      exit 0
      ;;
  esac
done

if [ $ECHO = "true" ]
then
  echo "Hello world";
fi
