#!/usr/bin/perl -CSD

use utf8;

@files = glob("*");

#print "list of all files is:\n";
#print @files;
#print "\n";

$count = 0;
foreach $file (@files)
{
    print "there is a file named: ".$file."\n";
    if ($file =~ /\p{Space}/)
    {
        print "found a match: ".$file."\n";
        $count++;
        $newfile = $file;
        $newfile =~ s/[\p{Space}]/_/g;
        print "proposed new file name is: ".$newfile."\n";
        #rename($file, $newfile) or warn "Could not rename $file: $!";
    }
}

if ( $count == 1 )
{
    print "1 file found \n";
}
else
{
    print "$count files found \n";
}

