#!/usr/bin/perl

use strict;
use warnings;
use open qw(:utf8 :std);
use Getopt::Long;

my $debug = 0;
my $verbose = 0;

GetOptions('d|debug' => \$debug, 'v|verbose' => \$verbose);

my @files = `ls`;

my $pattern = qr/[\p{Space}():;,]/;

my $count = 0;
my $file = '';
foreach $file (@files)
{
    chomp($file);
    if ( $verbose ) { print "there is a file named: ".$file."\n"; }
    if ($file =~ $pattern)
    {
        if ( $debug || $verbose ) { print "found a match: ".$file."\n"; }
        $count++;
        my $newfile = $file;
        $newfile =~ s/$pattern/_/g;
        if ( $debug || $verbose ) { print "proposed new file name is: ".$newfile."\n"; }
        if ( !$debug ) { rename($file, $newfile) or warn "Could not rename $file: $!"; }
    }
}

my $word = "changed";
if ( $debug ) { $word = "found"; }

if ( $count == 1 )
{
    print "1 file ".$word." \n";
}
else
{
    print "$count files ".$word." \n";
}

