#!/usr/bin/perl -CSD

use utf8;

@files = glob("*");

#print "list of all files is:\n";
#print @files;
#print "\n";

$count = 0;
foreach $file (@files)
{
    #if ($file =~ /[\x{0020}\x{202F}]/)
    if ($file =~ /\p{Space}/)
    {
        print "found a match: ".$file."\n";
        $count++;
        $newfile = $file;
        $newfile =~ s/[\x{0020}\x{202F}]/_/g;
        rename($file, $newfile) or warn "Could not rename $file: $!";
    }
}

if ( $count == 1 )
{
    print "1 file changed \n";
}
else
{
    print "$count files changed \n";
}

