#!/usr/bin/perl

use strict;
use warnings;



my ($old, $new) = @ARGV;

print "Old pattern is $old and new pattern is $new\n";

my @LIST = glob("$old\*");

my $size = @LIST;
my $zero = length($size);


my $index = 0;
foreach(@LIST)
{
    $index++;
    my $file = $_;
    chomp($file);
    my $newfile = sprintf("%s_%0*d.png",$new,$zero,$index);
    print "Old name is $file, new name is $newfile \n";
    system("mv $file $newfile");
}



if ( $size == 1 )
{
    print "1 file changed \n";
}
else
{
    print "$size files changed \n";
}

