#!/usr/bin/perl

$suffix_string = 'belmonrj@sftp.sdcc.bnl.gov:';

$input_string = $ARGV[0];

$command_string = 'sftp '.$suffix_string.' <<< $\'put '.$input_string.'\'';

print "Command string is $command_string \n\n";

system($command_string);

