#!/usr/bin/perl

$suffix_string = 'belmonrj@rftpexp.rhic.bnl.gov:';

$input_string = $ARGV[0];

$command_string = 'scp '.$input_string.' '.$suffix_string;

print "Command string is $command_string \n\n";

system($command_string);

