#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;

my @go_up;
my @come_down;
my $debug = 0;
my $verbose = 0;

GetOptions('d|down=s{1,}' => \@come_down, 'u|up=s{1,}' => \@go_up, 'debug' => \$debug, 'verbose' => \$verbose);

####################################

my $prefix_string = 'sftp belmonrj@sftp.sdcc.bnl.gov <<EOF'."\n";

####################################

my $up_string = '';
my $up_file;
foreach $up_file (@go_up)
{
    chomp($up_file);
    $up_string.="put ".$up_file."\n";
}

####################################

my $down_string = '';
my $down_file;
foreach $down_file (@come_down)
{
    chomp($down_file);
    $down_string.="get ".$down_file."\n";
}

####################################

my $suffix_string = "EOF\n";

my $command_string = $prefix_string.$up_string.$down_string.$suffix_string;

if ( $debug || $verbose )
{
    print "The final string is:\n".$command_string."\n";
}
if ( !$debug )
{
    system($command_string);
}

