#!/usr/bin/perl

use Getopt::Long;

@go_up;
@come_down;
$debug = 0;
$verbose = 0;

GetOptions('d|down=s{1,}' => \@come_down, 'u|up=s{1,}' => \@go_up, 'debug' => \$debug, 'verbose' => \$verbose);

####################################

$prefix_string = 'sftp belmonrj@sftp.sdcc.bnl.gov <<EOF'."\n";

####################################

$up_string = '';

foreach $up_file (@go_up)
{
    chomp($up_file);
    $up_string.="put ".$up_file."\n";
}

####################################

$down_string = '';

foreach $down_file (@come_down)
{
    chomp($down_file);
    $down_string.="get ".$down_file."\n";
}

####################################

$suffix_string = "EOF\n";

$command_string = $prefix_string.$up_string.$down_string.$suffix_string;

if ( $debug || $verbose )
{
    print "The final string is:\n".$command_string."\n";
}
if ( !$debug )
{
    system($command_string);
}

