#!/bin/csh -f

set prefix=`echo $OFFLINE_MAIN | awk -F '/' '{print $2}'`

if ( "$prefix" == "afs" ) then
    echo Currently using PHENIX environment
endif

if ( "$prefix" == "cvmfs" ) then
    echo Currently using sPHENIX environment
endif

