#!/bin/bash

# check if gdate is available
# if it is, use it, otherwise use date
# date works fine if it's GNU date, but BSD date may not work
if command -v gdate >/dev/null 2>&1; then
  DATE_CMD="gdate"
else
  DATE_CMD="date"
fi


SINCE_DATE=""
UNTIL_DATE=""

# use current date as default
NOW=$($DATE_CMD +%s)
SINCE=$NOW
UNTIL=$NOW

# put code here to set the since and/or until via shell script options
for arg in "$@"; do
  case "$arg" in
    --since=*)
      SINCE_DATE="${arg#--since=}"
      SINCE=$($DATE_CMD +%s --date="$SINCE_DATE")
      ;;
    --until=*)
      UNTIL_DATE="${arg#--until=}"
      UNTIL=$($DATE_CMD +%s --date="$UNTIL_DATE")
      ;;
    --help|-h)
      echo "Usage: $0 [--since=\"DATE\"] [--until=\"DATE\"]"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg"
      echo "Run with --help for usage."
      exit 1
      ;;
  esac
done

# debugging
echo "SINCE_DATE is $SINCE_DATE"
echo "UNTIL_DATE is $UNTIL_DATE"
echo "SINCE is $SINCE"
echo "UNTIL is $UNTIL"


# calculate the difference
DIFFERENCE=$(($UNTIL-$SINCE))



if [[ $SINCE -ne $NOW && $UNTIL -eq $NOW ]]
    then
    echo "It has been $DIFFERENCE since $SINCE_DATE"
elif [[ $SINCE -eq $NOW && $UNTIL -ne $NOW ]]
    then
    echo "It is $DIFFERENCE until $UNTIL_DATE"
elif [[ $SINCE -ne $NOW && $UNTIL -ne $NOW ]]
    then
    echo "The time difference between $SINCE_DATE and $UNTIL_DATE is $DIFFERENCE"
else
    echo "Unknown condition"
fi
