#!/bin/bash

# check if gdate is available
# if it is, use it, otherwise use date
# date works fine if it's GNU date, but BSD date may not work
if command -v gdate >/dev/null 2>&1; then
  DATE_CMD="gdate"
else
  DATE_CMD="date"
fi


SINCE_DATE=""
UNTIL_DATE=""

# use current date as default
NOW=$($DATE_CMD +%s)
SINCE=$NOW
UNTIL=$NOW

# loop over the arguments
# case seems to be the most elegant solution for setting the options
for arg in "$@"; do
  case "$arg" in
    --since=*)
      SINCE_DATE="${arg#--since=}"
      SINCE=$($DATE_CMD +%s --date="$SINCE_DATE")
      ;;
    --until=*)
      UNTIL_DATE="${arg#--until=}"
      UNTIL=$($DATE_CMD +%s --date="$UNTIL_DATE")
      ;;
    --help|-h)
      echo "Usage: $0 [--since=\"DATE\"] [--until=\"DATE\"]"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg"
      echo "Run with --help for usage."
      exit 1
      ;;
  esac
done

# calculate the difference
DIFFERENCE=$(($UNTIL-$SINCE))

# put code here to convert difference into something nice
DAYS=$(($DIFFERENCE/86400))
PART=$(($DIFFERENCE%86400))
HOURS=$((PART/3600))
PART=$((PART%3600))
MINUTES=$((PART/60))
SECONDS=$(($PART%60))

# now make the difference string to make it nice and readable
# less than a minute
if [ "$DIFFERENCE" -lt 60 ]
  then
  DIFFERENCE_STRING="$SECONDS second"
  if [ "$SECONDS" -ne 1 ]
    then
    DIFFERENCE_STRING+="s"
  fi
# less than an hour
elif [ "$DIFFERENCE" -lt 3600 ]
  then
  DIFFERENCE_STRING="$MINUTES minute"
  if [ "$MINUTES" -ne 1 ]
    then
    DIFFERENCE_STRING+="s"
  fi
  DIFFERENCE_STRING+=", $SECONDS second"
  if [ "$SECONDS" -ne 1 ]
    then
    DIFFERENCE_STRING+="s"
  fi
# less than a day
elif [ "$DIFFERENCE" -lt 86400 ]
  then
  DIFFERENCE_STRING="$HOURS hour"
  if [ "$HOURS" -ne 1 ]
    then
    DIFFERENCE_STRING+="s"
  fi
  DIFFERENCE_STRING+=", $MINUTES minute"
  if [ "$MINUTES" -ne 1 ]
    then
    DIFFERENCE_STRING+="s"
  fi
  DIFFERENCE_STRING+=", $SECONDS second"
  if [ "$SECONDS" -ne 1 ]
    then
     DIFFERENCE_STRING+="s"
  fi
# more than a day
else
  echo "Hello is anything happening in here?"
  echo "The number of seconds is $DIFFERENCE"
  DIFFERENCE_STRING="$DAYS day"
  if [ "$DAYS" -ne 1 ]
    then
    DIFFERENCE_STRING+="s"
  fi
  DIFFERENCE_STRING="$HOURS hour"
  if [ "$HOURS" -ne 1 ]
    then
    DIFFERENCE_STRING+="s"
  fi
  DIFFERENCE_STRING+=", $MINUTES minute"
  if [ "$MINUTES" -ne 1 ]
    then
    DIFFERENCE_STRING+="s"
  fi
  DIFFERENCE_STRING+=", $SECONDS second"
  if [ "$SECONDS" -ne 1 ]
    then
     DIFFERENCE_STRING+="s"
  fi
fi

# now print all that stuff to the screen
if [[ $SINCE -ne $NOW && $UNTIL -eq $NOW ]]
  then
  echo "It has been $DIFFERENCE_STRING since $SINCE_DATE"
elif [[ $SINCE -eq $NOW && $UNTIL -ne $NOW ]]
  then
  echo "It is $DIFFERENCE_STRING until $UNTIL_DATE"
elif [[ $SINCE -ne $NOW && $UNTIL -ne $NOW ]]
  then
  echo "The time difference between $SINCE_DATE and $UNTIL_DATE is $DIFFERENCE_STRING"
else
  echo "Unknown condition"
fi
